name: CI

on: ['push', 'pull_request']

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ci:
    runs-on: ubuntu-latest

    name: CI

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Set up PR environment
      if: github.event.number != null
      run: echo "PULL_REQUEST_ID=${{ github.event.number }}" >> $GITHUB_ENV

    - name: Install npm dependencies
      run: npm ci

    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt -r scripts/pdf/requirements.txt

    - name: Test
      run: npm test

    - name: Build
      run: bash scripts/build.sh

    - name: Build PDF
      if: github.repository == 'tldr-pages/tldr' && github.ref == 'refs/heads/main'
      run: |
        cd scripts/pdf/
        python render.py ../../pages -c solarized-light

    - name: Deploy
      if: github.repository == 'tldr-pages/tldr' && github.ref == 'refs/heads/main'
      run: bash scripts/deploy.sh
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
